# Generated by Django 4.0.3 on 2023-04-25 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hamal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(blank=True, max_length=200)),
                ('delayCause', models.CharField(blank=True, choices=[('VC', 'VC'), ('SOC', 'SOC'), ('PC', 'PC'), ('תקנ"ם', 'תקנ"ם'), ('VIP', 'VIP'), ('מצודה וחמ"לים', 'מצודה וחמ"לים'), ('סיסטם', 'סיסטם'), ('מחכים לציוד', 'מחכים לציוד'), ('אחר', 'אחר')], max_length=100, null=True)),
                ('Title', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=100)),
                ('ip', models.CharField(max_length=100)),
                ('boolChecks', models.JSONField(blank=True, null=True)),
                ('info', models.JSONField(blank=True, null=True)),
                ('hamalId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hamal.hamal')),
            ],
        ),
    ]
