# Generated by Django 4.0.3 on 2023-05-02 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='ip',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
