# Generated by Django 4.0.3 on 2023-05-02 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0002_alter_tool_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='Title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
