# Generated by Django 4.0.3 on 2023-04-25 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='default', max_length=200)),
                ('location', models.CharField(choices=[('מצודת ציון', 'מצודת ציון'), ('מרגנית', 'מרגנית'), ('בניין מטכ"ל', 'בניין מטכ"ל')], default=('מצודת ציון', 'מצודת ציון'), max_length=100)),
                ('mahlaka', models.CharField(choices=[('VC', 'VC'), ('מצודה וחמ"לים', 'מצודה וחמ"לים'), ('VIP', 'VIP'), ('תשתיות', 'תשתיות')], default=('VC', 'VC'), max_length=100)),
                ('isCritical', models.BooleanField(default=False)),
            ],
        ),
    ]
